data_params:
  all_genes: false
  data_dir: "../AGrEDA/data"
  dset: dlpfc
  n_markers: 20
  n_mix: 8
  n_spots: 100000
  scaler_name: minmax
  samp_split: true
  sc_id: GSE144136
  st_id: spatialLIBD
  st_split: false
lib_params: {}
model_params:
  celldart_kwargs: {}
  model_version: std
train_params:
  alpha: 0.6
  alpha_lr: 5
  batch_size: 512
  initial_train_epochs: 10
  n_iter: 15000
  pretraining: true
  reverse_val: true
