data_params:
  all_genes: false
  data_dir: "../AGrEDA/data"
  dset: pdac
  n_markers: 80
  n_mix: 70
  n_spots: 100000
  one_model: true
  samp_split: false
  sc_id: CA001063
  scaler_name: minmax
  st_id: GSE111672
  st_split: false
lib_params:
  manual_seed: 2123428735
model_params:
  celldart_kwargs:
    bn_momentum: 0.01
    emb_dim: 32
  model_version: gen_pdac-18486
train_params:
  alpha: 0.6
  alpha_lr: 5
  batch_size: 128
  initial_train_epochs: 10
  lr: 0.01
  n_iter: 15000
  pretraining: true
  reverse_val: false
