data_params:
  all_genes: false
  data_dir: "../AGrEDA/data"
  dset: mouse_cortex
  n_markers: 40
  n_mix: 5
  n_spots: 100000
  samp_split: true
  sc_id: GSE115746
  scaler_name: minmax
  st_id: spotless_mouse_cortex
  st_split: false
lib_params:
  manual_seed: 2305369564
model_params:
  celldart_kwargs:
    bn_momentum: 0.1
    emb_dim: 64
  model_version: gen_spotless_oracle-837
train_params:
  alpha: 0.6
  alpha_lr: 10
  batch_size: 8
  initial_train_epochs: 10
  lr: 0.01
  n_iter: 15000
  pretraining: true
  reverse_val: false
